import { Voice } from './echo';

export const MOCK_VOICE_VARIANTS: Voice[] = [
  { voice_id: "variant-1", name: "Lieke", category: "premade", labels: { language: "Dutch", accent: "Netherlands", use_case: "Customer Support" } },
  { voice_id: "variant-2", name: "Bram", category: "premade", labels: { language: "Dutch", accent: "Flemish", use_case: "Narrative" } },
  { voice_id: "variant-3", name: "Anke", category: "premade", labels: { language: "Dutch", accent: "Limburgish", use_case: "Conversational" } },
  { voice_id: "variant-4", name: "Thijs", category: "premade", labels: { language: "Dutch", accent: "Suriname", use_case: "News" } },
  { voice_id: "variant-5", name: "Mateo", category: "premade", labels: { language: "Spanish", accent: "Spain", use_case: "Professional" } },
  { voice_id: "variant-6", name: "Valeria", category: "premade", labels: { language: "Spanish", accent: "Mexico", use_case: "Social Media" } },
  { voice_id: "variant-7", name: "Santiago", category: "premade", labels: { language: "Spanish", accent: "Argentina", use_case: "E-learning" } },
  { voice_id: "variant-8", name: "Camila", category: "premade", labels: { language: "Spanish", accent: "Colombia", use_case: "Gaming" } },
  { voice_id: "variant-9", name: "Jean", category: "premade", labels: { language: "French", accent: "France", use_case: "Luxury" } },
  { voice_id: "variant-10", name: "Amélie", category: "premade", labels: { language: "French", accent: "Canada", use_case: "Children's Stories" } },
  { voice_id: "variant-11", name: "Lukas", category: "premade", labels: { language: "German", accent: "Germany", use_case: "Documentary" } },
  { voice_id: "variant-12", name: "Heidi", category: "premade", labels: { language: "German", accent: "Switzerland", use_case: "Tourism" } },
  { voice_id: "variant-13", name: "Aarav", category: "premade", labels: { language: "Hindi", accent: "Standard Hindi", use_case: "Corporate" } },
  { voice_id: "variant-14", name: "Ananya", category: "premade", labels: { language: "Hindi", accent: "Bhojpuri", use_case: "Radio" } },
  { voice_id: "variant-15", name: "Kenji", category: "premade", labels: { language: "Japanese", accent: "Tokyo", use_case: "Animation" } },
  { voice_id: "variant-16", name: "Sakura", category: "premade", labels: { language: "Japanese", accent: "Kyoto", use_case: "Traditional" } },
  { voice_id: "variant-17", name: "João", category: "premade", labels: { language: "Portuguese", accent: "Brazil", use_case: "Sports" } },
  { voice_id: "variant-18", name: "Beatriz", category: "premade", labels: { language: "Portuguese", accent: "Portugal", use_case: "Literature" } },
  { voice_id: "variant-19", name: "Luca", category: "premade", labels: { language: "Italian", accent: "Italy", use_case: "Cooking" } },
  { voice_id: "variant-20", name: "Giulia", category: "premade", labels: { language: "Italian", accent: "Switzerland", use_case: "Travel" } },
  { voice_id: "variant-21", name: "Wei", category: "premade", labels: { language: "Chinese", accent: "Mandarin", use_case: "Financial" } },
  { voice_id: "variant-22", name: "Mei-Ling", category: "premade", labels: { language: "Chinese", accent: "Cantonese", use_case: "Cinema" } },
  { voice_id: "variant-23", name: "Min-Jun", category: "premade", labels: { language: "Korean", accent: "Seoul", use_case: "K-Pop News" } },
  { voice_id: "variant-24", name: "Ji-Woo", category: "premade", labels: { language: "Korean", accent: "Busan", use_case: "Vlog" } },
  { voice_id: "variant-25", name: "Youssef", category: "premade", labels: { language: "Arabic", accent: "Egypt", use_case: "Politics" } },
  { voice_id: "variant-26", name: "Fatima", category: "premade", labels: { language: "Arabic", accent: "Levant", use_case: "Poetry" } },
  { voice_id: "variant-27", name: "Emre", category: "premade", labels: { language: "Turkish", accent: "Istanbul", use_case: "Tech Support" } },
  { voice_id: "variant-28", name: "Zeynep", category: "premade", labels: { language: "Turkish", accent: "Izmir", use_case: "Meditation" } },
  { voice_id: "variant-29", name: "Nguyen", category: "premade", labels: { language: "Vietnamese", accent: "Hanoi", use_case: "Education" } },
  { voice_id: "variant-30", name: "Linh", category: "premade", labels: { language: "Vietnamese", accent: "Ho Chi Minh", use_case: "E-commerce" } },
  { voice_id: "variant-31", name: "Budi", category: "premade", labels: { language: "Indonesian", accent: "Standard", use_case: "Government" } },
  { voice_id: "variant-32", name: "Sari", category: "premade", labels: { language: "Indonesian", accent: "Javanese", use_case: "Folk Stories" } },
  { voice_id: "variant-33", name: "Dmitry", category: "premade", labels: { language: "Russian", accent: "Russia", use_case: "Military" } },
  { voice_id: "variant-34", name: "Elena", category: "premade", labels: { language: "Russian", accent: "Kazakhstan", use_case: "Weather" } },
  { voice_id: "variant-35", name: "Maria", category: "premade", labels: { language: "Filipino", accent: "Tagalog", use_case: "Showbiz" } },
  { voice_id: "variant-36", name: "Juan", category: "premade", labels: { language: "Filipino", accent: "Cebuano", use_case: "Local News" } },
  { voice_id: "variant-37", name: "James", category: "premade", labels: { language: "English", accent: "USA", use_case: "Action Hero" } },
  { voice_id: "variant-38", name: "Emma", category: "premade", labels: { language: "English", accent: "UK", use_case: "Audiobook" } },
  { voice_id: "variant-39", name: "Liam", category: "premade", labels: { language: "English", accent: "Australia", use_case: "Outdoors" } },
  { voice_id: "variant-40", name: "Olivia", category: "premade", labels: { language: "English", accent: "Canada", use_case: "Healthcare" } },
  { voice_id: "variant-41", name: "Raj", category: "premade", labels: { language: "English", accent: "India", use_case: "IT Services" } },
  { voice_id: "variant-42", name: "Siobhan", category: "premade", labels: { language: "English", accent: "Ireland", use_case: "Mythology" } },
  { voice_id: "variant-43", name: "Thabo", category: "premade", labels: { language: "English", accent: "South Africa", use_case: "Inspiration" } },
  { voice_id: "variant-44", name: "Kiwi", category: "premade", labels: { language: "English", accent: "New Zealand", use_case: "Adventure" } },
  { voice_id: "variant-45", name: "Lee", category: "premade", labels: { language: "English", accent: "Singapore", use_case: "Urban" } },
  { voice_id: "variant-46", name: "Katarina", category: "premade", labels: { language: "Swedish", accent: "Sweden", use_case: "Design" } },
  { voice_id: "variant-47", name: "Soren", category: "premade", labels: { language: "Danish", accent: "Denmark", use_case: "Architecture" } },
  { voice_id: "variant-48", name: "Aino", category: "premade", labels: { language: "Finnish", accent: "Finland", use_case: "Nature" } },
  { voice_id: "variant-49", name: "Magnus", category: "premade", labels: { language: "Norwegian", accent: "Norway", use_case: "History" } },
  { voice_id: "variant-50", name: "Jakub", category: "premade", labels: { language: "Czech", accent: "Czech Republic", use_case: "Engineering" } },
  { voice_id: "variant-51", name: "Multilingual Alex", category: "premade", labels: { language: "Multilingual", accent: "Global", use_case: "Conversational" } },
  { voice_id: "variant-52", name: "Multilingual Sarah", category: "premade", labels: { language: "Multilingual", accent: "Global", use_case: "Professional" } },
  { voice_id: "variant-53", name: "Action Hero Jack", category: "premade", labels: { language: "English", accent: "USA", use_case: "Action Hero" } },
  { voice_id: "variant-54", name: "Adventure Mia", category: "premade", labels: { language: "English", accent: "USA", use_case: "Adventure" } },
  { voice_id: "variant-55", name: "Animation Spark", category: "premade", labels: { language: "English", accent: "USA", use_case: "Animation" } },
  { voice_id: "variant-56", name: "Storyteller Ben", category: "premade", labels: { language: "English", accent: "UK", use_case: "Audiobook" } },
  { voice_id: "variant-57", name: "Architect Finn", category: "premade", labels: { language: "Danish", accent: "Denmark", use_case: "Architecture" } },
  { voice_id: "variant-58", name: "Cooking Chef", category: "premade", labels: { language: "Italian", accent: "Italy", use_case: "Cooking" } },
  { voice_id: "variant-59", name: "Tech Support Guru", category: "premade", labels: { language: "English", accent: "India", use_case: "Tech Support" } },
  { voice_id: "variant-60", name: "Vlog Star", category: "premade", labels: { language: "Korean", accent: "Seoul", use_case: "Vlog" } },
];
